import { Collaborator } from '../types';

export const IMPORTED_COLLABORATORS: Omit<Collaborator, 'id' | 'updatedAt'>[] = [
  { registration: "1487", name: "ADAIAS DE ALENCAR MELO", role: "Supervisor de Produção" },
  { registration: "1849", name: "ADMILSON SENA DA SILVA", role: "Operador I" },
  { registration: "1695", name: "ADRIANO BRASIL SARAIVA", role: "Conferente I" },
  { registration: "1777", name: "ADRIANO CARDOSO CABRAL", role: "Operador de Empilhadeira" },
  { registration: "1834", name: "ADRIANO DA SILVA MACIEL", role: "Auxiliar de Produção" },
  { registration: "1796", name: "ALESSANDRO DE BRITO MARQUES", role: "Auxiliar de Produção" },
  { registration: "1872", name: "ALESSANDRO NUNES DA SILVA", role: "Auxiliar de Produção" },
  { registration: "1838", name: "ALEXANDER JOSE VASQUEZ AGUILAR", role: "Mecânico de Manutenção II" },
  { registration: "1549", name: "ALISON DE SOUZA ACIPAR", role: "Assistente de Logística" },
  { registration: "1867", name: "ANA VICENCIA BARBOSA GOMES", role: "Responsável Técnico Químico" },
  { registration: "1575", name: "ANDRE PAULO DA SILVA", role: "Operador I" },
  { registration: "1785", name: "ANTONIO CARLOS RODRIGUES DO NASCIMENTO", role: "Auxiliar de Produção" },
  { registration: "1812", name: "ANTONIO VICTOR RODRIGUES DE SOUZA", role: "Auxiliar Administrativo" },
  { registration: "1855", name: "ARINETO ALVES DE ANDRADE", role: "Auxiliar de Produção" },
  { registration: "1828", name: "CARLOS ALBERTO DUARTE DOS ANJOS", role: "Auxiliar de Produção" },
  { registration: "1876", name: "CARLOS DA CONCEICAO FERREIRA", role: "Auxiliar de Produção" },
  { registration: "1698", name: "CARLOS PHILLIP BATISTA DA SILVA", role: "Operador de Extrusora I" },
  { registration: "1807", name: "CHRISTIAN DA SILVA PIMENTEL", role: "Operador de Extrusora I" },
  { registration: "1673", name: "CIDONEIDE OLIVEIRA DE LIMA", role: "Operador de Extrusora I" },
  { registration: "1716", name: "CLAUDIO DE LIMA SOBRAL", role: "Auxiliar de Extrusora" },
  { registration: "1877", name: "CLEITON JOSUE DE OLIVEIRA DA SILVA", role: "Auxiliar de Produção" },
  { registration: "1866", name: "DANIEL DA SILVA ARAGAO", role: "Analista Incentivos Fiscais" },
  { registration: "1607", name: "DEYWIS JUNIO SOUZA MENEZES", role: "Operador de Extrusora I" },
  { registration: "1856", name: "DIONISON FONSECA CORREA", role: "Auxiliar de Produção" },
  { registration: "1775", name: "EDER CARDOSO PEREIRA", role: "Operador de Empilhadeira" },
  { registration: "1662", name: "EDILSON DA SILVA BENTES", role: "Operador de Extrusora I" },
  { registration: "1544", name: "ELY ANDREY BATISTA DA SILVA", role: "Assistente de Expedição" },
  { registration: "1792", name: "ENDREY LIMA VIANA", role: "Auxiliar de Produção" },
  { registration: "1829", name: "ERITON OLIVEIRA DE MERCES", role: "Eletricista de Manutenção II" },
  { registration: "1745", name: "ERIVAN FONTES DE SOUZA", role: "Operador de Extrusora II" },
  { registration: "1555", name: "ERNAN COELHO DE SOUZA", role: "Líder de Manutenção" },
  { registration: "1794", name: "EVERSON PEREIRA DA SILVA", role: "Operador de Extrusora II" },
  { registration: "1806", name: "FABIO ANDRE BELCHIOR MATOS", role: "Operador de Erema" },
  { registration: "1854", name: "FILIPE APARICIO DE SOUZA", role: "Analista Logística e Transp" },
  { registration: "1868", name: "FILIPE DE SOUZA MESQUITA", role: "Aprendiz" },
  { registration: "1840", name: "FRANCISCO GEOVANY MOREIRA DA SILVA", role: "Operador I" },
  { registration: "1859", name: "GENISON GOMES DA SILVA", role: "Auxiliar de Produção" },
  { registration: "1844", name: "GILCIMAR CARLOS CORREA ARAUJO", role: "Operador de Erema" },
  { registration: "1850", name: "GREISIANE PONTES OLIVEIRA", role: "Técnico Segurança do Trabalho" },
  { registration: "1862", name: "GUSTAVO OLIVEIRA DA SILVA", role: "Aprendiz" },
  { registration: "1768", name: "IVANILDO PALMERIO DOS SANTOS", role: "Operador de Empilhadeira II" },
  { registration: "1660", name: "JANDESON MIRANDA CARDOSO", role: "Auxiliar de Serviços Gerais" },
  { registration: "1801", name: "JOAO AUGUSTO CARVALHO DIAS", role: "Auxiliar de Produção" },
  { registration: "1736", name: "JOAO VITOR CARVALHO DE MORAES", role: "Auxiliar de Produção" },
  { registration: "1842", name: "JOAO VITOR DE ANDRADE SOUZA", role: "Auxiliar de Produção" },
  { registration: "1861", name: "JONATHAS TIAGO FERREIRA NOGUEIRA", role: "Auxiliar de Produção" },
  { registration: "1874", name: "JORDANIA BATALHA DE LIMA", role: "Analista de PCP" },
  { registration: "1795", name: "JORGE BARBOSA OLIVEIRA", role: "Operador I" },
  { registration: "1833", name: "JURIGLEISON MARICAUA DE LIMA", role: "Auxiliar de Manutenção Predial" },
  { registration: "1702", name: "KEVEN AUGUSTO SILVA E SILVA", role: "Operador I" },
  { registration: "1831", name: "LADMO VALUCE DA SILVA SOUSA", role: "Operador de Empilhadeira" },
  { registration: "1808", name: "LENO DA SILVA FERREIRA", role: "Auxiliar de Produção" },
  { registration: "1847", name: "LUIZ EDUARDO SANTANA CORREA", role: "Auxiliar de Produção" },
  { registration: "1611", name: "MARCELO DA SILVA CASTRO", role: "Operador de Extrusora I" },
  { registration: "1694", name: "MARCIO PONTES NEVES", role: "Auxiliar de Produção" },
  { registration: "1857", name: "MARIO SANTOS DA SILVA JUNIOR", role: "Operador I" },
  { registration: "1815", name: "MARLON WILLIAN SANTANA CORREA", role: "Eletricista de Manutenção II" },
  { registration: "1622", name: "MAURIZIO TAGLIATTI", role: "Diretor" },
  { registration: "1704", name: "NAHIM VIEIRA DA SILVA", role: "Operador de Extrusora I" },
  { registration: "1798", name: "NAZARENO SOUZA VITORIA", role: "Operador de Empilhadeira" },
  { registration: "1725", name: "OEULER FERREIRA SOARES", role: "Auxiliar de Produção" },
  { registration: "1608", name: "ONELSON OLIVEIRA TAVARES", role: "Operador de Empilhadeira II" },
  { registration: "1606", name: "PALOMA REIS DE MAGALHAES SOUZA", role: "Analista Administrativo" },
  { registration: "1865", name: "PAULO GUILHERME GONCALVES SANTOS", role: "Auxiliar de Produção" },
  { registration: "1827", name: "PAULO VITOR BARROS DE SOUZA", role: "Auxiliar de Produção" },
  { registration: "1873", name: "RAILA BATISTA SANTOS", role: "Auxiliar de Produção" },
  { registration: "1852", name: "RAILTO GONCALVES SOARES", role: "Mecânico de Manutenção II" },
  { registration: "1822", name: "RAIMUNDO MANDUCA DE SOUZA", role: "Mecânico de Manutenção II" },
  { registration: "1858", name: "RENILDO QUINTANILHA DE MIRANDA", role: "Auxiliar de Produção" },
  { registration: "1707", name: "RODRIGO DE SOUZA DUTRA", role: "Técnico de Manutenção III" },
  { registration: "1845", name: "SEBASTIAO MOURA DE OLIVEIRA", role: "Eletricista de Manutenção II" },
  { registration: "1871", name: "SERGIO VITOR COSTA D ALMEIDA", role: "Eletricista de Manutenção II" },
  { registration: "1863", name: "TIAGO BARGAS MONTEIRO", role: "Auxiliar de Produção" },
  { registration: "1758", name: "VALNEI PEREIRA COELHO", role: "Mecânico de Manutenção" },
  { registration: "1870", name: "WILDEMBERG DA SILVA SILVEIRA", role: "Mecânico de Manutenção" }
];
